# Generated by Django 3.0.7 on 2021-01-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashareAll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstock_a',
            name='stock_name',
        ),
    ]
